# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'matplotlibgui2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TabPlots(object):
    def setupUi(self, TabPlots):
        TabPlots.setObjectName("TabPlots")
        TabPlots.resize(493, 376)
        TabPlots.setAccessibleName("")
        self.plot_fits = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_fits.sizePolicy().hasHeightForWidth())
        self.plot_fits.setSizePolicy(sizePolicy)
        self.plot_fits.setObjectName("plot_fits")
        self.gridLayout = QtWidgets.QGridLayout(self.plot_fits)
        self.gridLayout.setObjectName("gridLayout")
        self.plot_fits_stackedWidget = QtWidgets.QStackedWidget(self.plot_fits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_fits_stackedWidget.sizePolicy().hasHeightForWidth())
        self.plot_fits_stackedWidget.setSizePolicy(sizePolicy)
        self.plot_fits_stackedWidget.setObjectName("plot_fits_stackedWidget")
        self.page_0 = MplWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_0.sizePolicy().hasHeightForWidth())
        self.page_0.setSizePolicy(sizePolicy)
        self.page_0.setObjectName("page_0")
        self.plot_fits_stackedWidget.addWidget(self.page_0)
        self.page_1 = MplWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_1.sizePolicy().hasHeightForWidth())
        self.page_1.setSizePolicy(sizePolicy)
        self.page_1.setObjectName("page_1")
        self.plot_fits_stackedWidget.addWidget(self.page_1)
        self.page_2 = MplWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_2.sizePolicy().hasHeightForWidth())
        self.page_2.setSizePolicy(sizePolicy)
        self.page_2.setObjectName("page_2")
        self.plot_fits_stackedWidget.addWidget(self.page_2)
        self.page_3 = MplWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_3.sizePolicy().hasHeightForWidth())
        self.page_3.setSizePolicy(sizePolicy)
        self.page_3.setObjectName("page_3")
        self.plot_fits_stackedWidget.addWidget(self.page_3)
        self.page_4 = MplWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_4.sizePolicy().hasHeightForWidth())
        self.page_4.setSizePolicy(sizePolicy)
        self.page_4.setObjectName("page_4")
        self.plot_fits_stackedWidget.addWidget(self.page_4)
        self.page_5 = MplWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_5.sizePolicy().hasHeightForWidth())
        self.page_5.setSizePolicy(sizePolicy)
        self.page_5.setObjectName("page_5")
        self.plot_fits_stackedWidget.addWidget(self.page_5)
        self.page_6 = MplWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_6.sizePolicy().hasHeightForWidth())
        self.page_6.setSizePolicy(sizePolicy)
        self.page_6.setObjectName("page_6")
        self.plot_fits_stackedWidget.addWidget(self.page_6)
        self.page_7 = MplWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_7.sizePolicy().hasHeightForWidth())
        self.page_7.setSizePolicy(sizePolicy)
        self.page_7.setObjectName("page_7")
        self.plot_fits_stackedWidget.addWidget(self.page_7)
        self.page_8 = MplWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_8.sizePolicy().hasHeightForWidth())
        self.page_8.setSizePolicy(sizePolicy)
        self.page_8.setObjectName("page_8")
        self.plot_fits_stackedWidget.addWidget(self.page_8)
        self.gridLayout.addWidget(self.plot_fits_stackedWidget, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(414, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.prev = QtWidgets.QPushButton(self.plot_fits)
        self.prev.setMaximumSize(QtCore.QSize(21, 26))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.prev.setFont(font)
        self.prev.setFlat(True)
        self.prev.setObjectName("prev")
        self.gridLayout.addWidget(self.prev, 1, 1, 1, 1)
        self.sig = QtWidgets.QPushButton(self.plot_fits)
        self.sig.setMaximumSize(QtCore.QSize(21, 26))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sig.setFont(font)
        self.sig.setFlat(True)
        self.sig.setObjectName("sig")
        self.gridLayout.addWidget(self.sig, 1, 2, 1, 1)
        TabPlots.addTab(self.plot_fits, "")
        self.plot_param = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_param.sizePolicy().hasHeightForWidth())
        self.plot_param.setSizePolicy(sizePolicy)
        self.plot_param.setAccessibleName("")
        self.plot_param.setObjectName("plot_param")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.plot_param)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plot_param_stackedWidget = QtWidgets.QStackedWidget(self.plot_param)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_param_stackedWidget.sizePolicy().hasHeightForWidth())
        self.plot_param_stackedWidget.setSizePolicy(sizePolicy)
        self.plot_param_stackedWidget.setObjectName("plot_param_stackedWidget")
        self.page_9 = MplWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_9.sizePolicy().hasHeightForWidth())
        self.page_9.setSizePolicy(sizePolicy)
        self.page_9.setObjectName("page_9")
        self.plot_param_stackedWidget.addWidget(self.page_9)
        self.page_10 = MplWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_10.sizePolicy().hasHeightForWidth())
        self.page_10.setSizePolicy(sizePolicy)
        self.page_10.setObjectName("page_10")
        self.plot_param_stackedWidget.addWidget(self.page_10)
        self.gridLayout_2.addWidget(self.plot_param_stackedWidget, 0, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(414, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.prev_2 = QtWidgets.QPushButton(self.plot_param)
        self.prev_2.setMaximumSize(QtCore.QSize(21, 26))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.prev_2.setFont(font)
        self.prev_2.setFlat(True)
        self.prev_2.setObjectName("prev_2")
        self.gridLayout_2.addWidget(self.prev_2, 1, 1, 1, 1)
        self.sig_2 = QtWidgets.QPushButton(self.plot_param)
        self.sig_2.setMaximumSize(QtCore.QSize(21, 26))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.sig_2.setFont(font)
        self.sig_2.setFlat(True)
        self.sig_2.setObjectName("sig_2")
        self.gridLayout_2.addWidget(self.sig_2, 1, 2, 1, 1)
        TabPlots.addTab(self.plot_param, "")

        self.retranslateUi(TabPlots)
        TabPlots.setCurrentIndex(1)
        self.plot_fits_stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabPlots)

    def retranslateUi(self, TabPlots):
        _translate = QtCore.QCoreApplication.translate
        TabPlots.setWindowTitle(_translate("TabPlots", "Imágenes"))
        self.prev.setText(_translate("TabPlots", "◀"))
        self.sig.setText(_translate("TabPlots", "▶"))
        TabPlots.setTabText(TabPlots.indexOf(self.plot_fits), _translate("TabPlots", "Fits"))
        self.prev_2.setText(_translate("TabPlots", "◀"))
        self.sig_2.setText(_translate("TabPlots", "▶"))
        TabPlots.setTabText(TabPlots.indexOf(self.plot_param), _translate("TabPlots", "Gráficos"))

from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabPlots = QtWidgets.QTabWidget()
    ui = Ui_TabPlots()
    ui.setupUi(TabPlots)
    TabPlots.show()
    sys.exit(app.exec_())

